// <auto-generated />
using System;
using System.Collections.Generic;
using Maliev.UploadService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.UploadService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UploadDbContext))]
    [Migration("20251217165454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.UploadService.Domain.Entities.BulkDeleteJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteFilesOlderThan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_files_older_than");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_details");

                    b.PrimitiveCollection<List<string>>("Errors")
                        .HasColumnType("text[]")
                        .HasColumnName("errors");

                    b.Property<int>("FilesDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("files_deleted");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("integer")
                        .HasColumnName("files_failed");

                    b.Property<int>("FilesProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("files_processed");

                    b.Property<int>("FilesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("files_total");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initiated_by");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path_prefix");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer")
                        .HasColumnName("total_files");

                    b.PrimitiveCollection<List<string>>("UploadIds")
                        .HasColumnType("text[]")
                        .HasColumnName("upload_ids");

                    b.HasKey("JobId")
                        .HasName("pk_bulk_delete_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_bulk_delete_created_at");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_bulk_delete_service_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_bulk_delete_status");

                    b.ToTable("bulk_delete_jobs", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RetentionPolicyId")
                        .HasColumnType("text")
                        .HasColumnName("retention_policy_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("StorageClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_class");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upload_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("VersionETag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_e_tag");

                    b.HasKey("FileId")
                        .HasName("pk_file_metadata");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_filemetadata_expires_at");

                    b.HasIndex("RetentionPolicyId")
                        .HasDatabaseName("ix_file_metadata_retention_policy_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_filemetadata_service_id");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("idx_filemetadata_storage_path");

                    b.HasIndex("UploadId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_metadata_upload_id");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("idx_filemetadata_uploaded_at");

                    b.ToTable("file_metadata", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Domain.Entities.RetentionPolicy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("ApplyToPathPrefix")
                        .HasColumnType("text")
                        .HasColumnName("apply_to_path_prefix");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_name");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("StorageClassTransitions")
                        .HasColumnType("jsonb")
                        .HasColumnName("storage_class_transitions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PolicyId")
                        .HasName("pk_retention_policies");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_retention_policy_is_active");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_retention_policy_service_id");

                    b.ToTable("retention_policies", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Domain.Entities.ServiceAuthorizationPolicy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<bool>("AllowOverwrite")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_overwrite");

                    b.Property<bool>("AllowResumableUpload")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_resumable_upload");

                    b.Property<string>("AllowedContentTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_content_types");

                    b.Property<string>("AllowedPathPrefixes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_path_prefixes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("MaxFileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_file_size_bytes");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<long>("StorageQuotaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_quota_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PolicyId")
                        .HasName("pk_service_authorization_policies");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_authz_policy_is_active");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasDatabaseName("idx_authz_policy_service_id");

                    b.ToTable("service_authorization_policies", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Domain.Entities.Upload", b =>
                {
                    b.Property<string>("UploadId")
                        .HasColumnType("text")
                        .HasColumnName("upload_id");

                    b.Property<long>("BytesUploaded")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_uploaded");

                    b.Property<string>("Checksum")
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RetentionPolicyId")
                        .HasColumnType("text")
                        .HasColumnName("retention_policy_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("SessionUri")
                        .HasColumnType("text")
                        .HasColumnName("session_uri");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("UploadId")
                        .HasName("pk_uploads");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_uploads_service_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_uploads_status");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("idx_uploads_storage_path");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("idx_uploads_uploaded_at");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Domain.Entities.UploadEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text")
                        .HasColumnName("error_details");

                    b.Property<string>("EventResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_result");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<string>("UploadId")
                        .HasColumnType("text")
                        .HasColumnName("upload_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("EventId")
                        .HasName("pk_upload_events");

                    b.HasIndex("EventTimestamp")
                        .HasDatabaseName("idx_upload_events_timestamp");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_upload_events_event_type");

                    b.HasIndex("FileId")
                        .HasDatabaseName("idx_upload_events_file_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_upload_events_service_id");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("idx_upload_events_upload_id");

                    b.ToTable("upload_events", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Domain.Entities.FileMetadata", b =>
                {
                    b.HasOne("Maliev.UploadService.Domain.Entities.RetentionPolicy", "RetentionPolicy")
                        .WithMany()
                        .HasForeignKey("RetentionPolicyId")
                        .HasConstraintName("fk_file_metadata_retention_policies_retention_policy_id");

                    b.HasOne("Maliev.UploadService.Domain.Entities.Upload", null)
                        .WithOne()
                        .HasForeignKey("Maliev.UploadService.Domain.Entities.FileMetadata", "UploadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_metadata_uploads_upload_id");

                    b.Navigation("RetentionPolicy");
                });
#pragma warning restore 612, 618
        }
    }
}
