// <auto-generated />
using System;
using System.Collections.Generic;
using Maliev.UploadService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.UploadService.Api.Data.Migrations
{
    [DbContext(typeof(UploadServiceDbContext))]
    [Migration("20251208210553_FixErrorDetailsNullability")]
    partial class FixErrorDetailsNullability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.UploadService.Api.Models.Entities.BulkDeleteJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteFilesOlderThan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("Errors")
                        .HasColumnType("text[]");

                    b.Property<int>("FilesDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("integer");

                    b.Property<int>("FilesProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("FilesTotal")
                        .HasColumnType("integer");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("UploadIds")
                        .HasColumnType("text[]");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_bulk_delete_created_at");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_bulk_delete_service_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_bulk_delete_status");

                    b.ToTable("bulk_delete_jobs", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Api.Models.Entities.FileMetadata", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("RetentionPolicyId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VersionETag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_filemetadata_expires_at");

                    b.HasIndex("RetentionPolicyId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_filemetadata_service_id");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("idx_filemetadata_storage_path");

                    b.HasIndex("UploadId")
                        .IsUnique();

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("idx_filemetadata_uploaded_at");

                    b.ToTable("file_metadata", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Api.Models.Entities.RetentionPolicy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<string>("ApplyToPathPrefix")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<string>("StorageClassTransitions")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PolicyId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_retention_policy_is_active");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_retention_policy_service_id");

                    b.ToTable("retention_policies", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Api.Models.Entities.ServiceAuthorizationPolicy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<bool>("AllowOverwrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowResumableUpload")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedContentTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AllowedPathPrefixes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("MaxFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StorageQuotaBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PolicyId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_authz_policy_is_active");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasDatabaseName("idx_authz_policy_service_id");

                    b.ToTable("service_authorization_policies", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Api.Models.Entities.Upload", b =>
                {
                    b.Property<string>("UploadId")
                        .HasColumnType("text");

                    b.Property<long>("BytesUploaded")
                        .HasColumnType("bigint");

                    b.Property<string>("Checksum")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("RetentionPolicyId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionUri")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("UploadId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_uploads_service_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_uploads_status");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("idx_uploads_storage_path");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("idx_uploads_uploaded_at");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Api.Models.Entities.UploadEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<string>("EventResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text");

                    b.Property<string>("UploadId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("EventTimestamp")
                        .HasDatabaseName("idx_upload_events_timestamp");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_upload_events_event_type");

                    b.HasIndex("FileId")
                        .HasDatabaseName("idx_upload_events_file_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_upload_events_service_id");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("idx_upload_events_upload_id");

                    b.ToTable("upload_events", (string)null);
                });

            modelBuilder.Entity("Maliev.UploadService.Api.Models.Entities.FileMetadata", b =>
                {
                    b.HasOne("Maliev.UploadService.Api.Models.Entities.RetentionPolicy", "RetentionPolicy")
                        .WithMany()
                        .HasForeignKey("RetentionPolicyId");

                    b.HasOne("Maliev.UploadService.Api.Models.Entities.Upload", null)
                        .WithOne()
                        .HasForeignKey("Maliev.UploadService.Api.Models.Entities.FileMetadata", "UploadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RetentionPolicy");
                });
#pragma warning restore 612, 618
        }
    }
}
