name: PR Validation

on:
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x"

      - name: Restore dependencies
        run: dotnet restore Maliev.UploadService.slnx
        env:
          NUGET_USERNAME: ${{ github.actor }}
          NUGET_PASSWORD: ${{ secrets.GITOPS_PAT }}
          SHARED_LIBRARY_VERSION: ${{ github.base_ref == 'main' && '1.0.*' || '1.0.*-*' }}

      - name: Build
        run: dotnet build Maliev.UploadService.slnx --no-restore --configuration Release
        env:
          SharedLibraryVersion: ${{ github.base_ref == 'main' && '1.0.*' || '1.0.*-*' }}

      - name: Test
        run: dotnet test Maliev.UploadService.slnx --no-build --configuration Release --verbosity normal
        working-directory: ${{ github.workspace }}
