// <auto-generated />
using System;
using Maliev.SupplierService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.SupplierService.Data.Migrations
{
    [DbContext(typeof(SupplierDbContext))]
    [Migration("20251122001258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.MaterialCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_material_categories_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_material_categories_name");

                    b.ToTable("material_categories", (string)null);
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.OnboardingStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("TransitionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transitioned_at");

                    b.Property<string>("TransitionedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transitioned_by");

                    b.Property<string>("TransitionedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transitioned_by_name");

                    b.HasKey("Id");

                    b.HasIndex("Stage")
                        .HasDatabaseName("ix_onboarding_statuses_stage");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_onboarding_statuses_supplier_id");

                    b.HasIndex("TransitionedAt")
                        .HasDatabaseName("ix_onboarding_statuses_transitioned_at");

                    b.ToTable("onboarding_statuses", (string)null);
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.PerformanceEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EvaluationDate")
                        .HasColumnType("date")
                        .HasColumnName("evaluation_date");

                    b.Property<string>("EvaluatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("evaluator_id");

                    b.Property<string>("EvaluatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("evaluator_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("RatingCategory")
                        .HasColumnType("integer")
                        .HasColumnName("rating_category");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationDate")
                        .HasDatabaseName("ix_performance_evaluations_evaluation_date");

                    b.HasIndex("RatingCategory")
                        .HasDatabaseName("ix_performance_evaluations_rating_category");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_performance_evaluations_supplier_id");

                    b.ToTable("performance_evaluations", null, t =>
                        {
                            t.HasCheckConstraint("ck_performance_evaluations_score", "score >= 1 AND score <= 5");
                        });
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_order_date");

                    b.Property<int>("OnboardingStage")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_stage");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("ix_suppliers_company_name");

                    b.HasIndex("OnboardingStage")
                        .HasDatabaseName("ix_suppliers_onboarding_stage");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_suppliers_status");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_tax_id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("change_type");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("ChangedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by_name");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_supplier_audit_logs_changed_by");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_audit_logs_supplier_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_supplier_audit_logs_timestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_supplier_audit_logs_entity_type_entity_id");

                    b.ToTable("supplier_audit_logs", (string)null);
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_supplier_capabilities_name");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_capabilities_supplier_id");

                    b.ToTable("supplier_capabilities", (string)null);
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("document_name");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("ExternalFileRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_file_ref");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("ix_supplier_certifications_document_type");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("ix_supplier_certifications_expiration_date");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_certifications_supplier_id");

                    b.ToTable("supplier_certifications", (string)null);
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_supplier_contacts_email");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_contacts_supplier_id");

                    b.ToTable("supplier_contacts", (string)null);
                });

            modelBuilder.Entity("supplier_material_categories", b =>
                {
                    b.Property<Guid>("supplier_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("material_category_id")
                        .HasColumnType("uuid");

                    b.HasKey("supplier_id", "material_category_id");

                    b.HasIndex("material_category_id")
                        .HasDatabaseName("ix_supplier_material_categories_category_id");

                    b.ToTable("supplier_material_categories");
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.OnboardingStatus", b =>
                {
                    b.HasOne("Maliev.SupplierService.Data.Entities.Supplier", "Supplier")
                        .WithMany("OnboardingHistory")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.PerformanceEvaluation", b =>
                {
                    b.HasOne("Maliev.SupplierService.Data.Entities.Supplier", "Supplier")
                        .WithMany("Evaluations")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierAuditLog", b =>
                {
                    b.HasOne("Maliev.SupplierService.Data.Entities.Supplier", "Supplier")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierCapability", b =>
                {
                    b.HasOne("Maliev.SupplierService.Data.Entities.Supplier", "Supplier")
                        .WithMany("Capabilities")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierCertification", b =>
                {
                    b.HasOne("Maliev.SupplierService.Data.Entities.Supplier", "Supplier")
                        .WithMany("Certifications")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.SupplierContact", b =>
                {
                    b.HasOne("Maliev.SupplierService.Data.Entities.Supplier", "Supplier")
                        .WithMany("Contacts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("supplier_material_categories", b =>
                {
                    b.HasOne("Maliev.SupplierService.Data.Entities.MaterialCategory", null)
                        .WithMany()
                        .HasForeignKey("material_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maliev.SupplierService.Data.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("supplier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.SupplierService.Data.Entities.Supplier", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Capabilities");

                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Evaluations");

                    b.Navigation("OnboardingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
